CREATE TABLE IF NOT EXISTS REST_DB_ACCESS(ID INT PRIMARY KEY, NAME VARCHAR(25),PASSWORD VARCHAR(25),ROLE  VARCHAR(25));

INSERT INTO REST_DB_ACCESS(ID, NAME, PASSWORD, ROLE) VALUES (1, 'admin', 'geheim247', 'admin')
INSERT INTO REST_DB_ACCESS(ID, NAME, PASSWORD, ROLE) VALUES (2, 'guest', 'geheim247', 'guest')
INSERT INTO REST_DB_ACCESS(ID, NAME, PASSWORD, ROLE) VALUES (4, 'gareng', 'geheim247', 'user')
